### ISSUE TITLE
[ENHANCEMENT] Allow reloading of an avatar after whitelisting it without needing to rejoin the instance

### ISSUE THREAD

**Issue by SouljaVR** [autumncpp/void-issues#57] opened 2022-05-08 23:21 UTC
As of now you need to rejoin the instance you are in to see someones avatar correctly after whitelisting it. Most of the time this is pretty inconvenient and can even be detrimental to the experience if you need to rejoin an almost full instance. Makes my game completely sh*t itself having to reload all those people into memory again just to see one person. Maybe an extra void avatar reload button could be added, that does a 'true' reload unlike just hiding/showing someones avatar.

**Comment by autumncpp** [comment] 2022-06-14 06:48
Duplicate of https://github.com/autumncpp/void-issues/issues/52

**Closed by autumncpp** 2022-06-14 06:48 UTC
Labels: enhancement
